# Generated by Django 4.2.5 on 2023-09-28 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.detail


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_author_book_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetailView',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.book')),
            ],
            bases=(django.views.generic.detail.DetailView, 'catalog.book'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
